apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "stock-trader"
  labels:
    app.kubernetes.io/version: "3"
spec:
  selector:
    matchLabels:
     solution: "stock-trader"
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
  descriptor:
    type: "stock-trader"
    version: "4.9.4"
    description: "stock-trader is open source software you can use perform stock trades"
    icons: 
      - src: "https://example.com/stock-trader.png"
        type: "image/png"
    assemblyPhase: "Pending"
    maintainers:
      - name:  Bugs Bunny
        email: bugsbunny@github.com
    owners:
      - name:  Bugs Bunny
        email: bugsbunny@github.com
    keywords:
      - "stock-trader"
    links:
      - description: About
        url: "https://stock-trader.org/"
      - description: Web Server Dashboard
        url: "https://metrics/internal/stock-trader/web-app"
      - description: Mysql Dashboard
        url: "https://metrics/internal/stock-trader/mysql"